- hosts: kubeadm01
  become: true
  tasks:
    - name: Run kubeadm
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr=172.16.0.0/16 --cri-socket=unix://var/run/cri-dockerd.sock --control-plane-endpoint 10.42.1.70:6443 --upload-certs